import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { execSync } from 'node:child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const toAbsolute = (p) => path.resolve(__dirname, p);

async function run() {
  console.log('Building client bundle...');
  execSync('npx vite build --outDir dist/client', { stdio: 'inherit', cwd: __dirname });

  console.log('Building server bundle...');
  execSync('npx vite build --ssr src/entry-server.jsx --outDir dist/server', { stdio: 'inherit', cwd: __dirname });

  // Import the render function from the server bundle using file:// URL for Windows compatibility
  const serverEntryPath = pathToFileURL(toAbsolute('./dist/server/entry-server.js')).href;
  const { render } = await import(serverEntryPath);

  // Read index.html generated by the client build
  const template = fs.readFileSync(toAbsolute('./dist/client/index.html'), 'utf-8');

  // Define public routes to prerender
  const routesToPrerender = [
    '/',
    '/login',
    '/register',
    '/forgot-password',
    '/reset-password',
    '/404',
  ];

  console.log(`Prerendering ${routesToPrerender.length} routes...`);

  for (const url of routesToPrerender) {
    const helmetContext = {};
    const { html } = render(url, helmetContext);
    const { helmet } = helmetContext;

    // Build the page meta tags from Helmet
    const helmetTags = [
      helmet?.title?.toString() || '',
      helmet?.meta?.toString() || '',
      helmet?.link?.toString() || '',
      helmet?.script?.toString() || '',
    ].join('\n');

    // Replace the placeholders in the index.html template
    let renderedHtml = template
      .replace('<div id="root"></div>', `<div id="root">${html}</div>`)
      .replace('</head>', `${helmetTags}\n</head>`);

    // Extract HTML attributes from Helmet if present
    if (helmet?.htmlAttributes) {
      const htmlAttrs = helmet.htmlAttributes.toString();
      if (htmlAttrs) {
        renderedHtml = renderedHtml.replace('<html lang="en"', `<html lang="en" ${htmlAttrs}`);
      }
    }

    // Determine output filename and directory
    let fileName;
    if (url === '/') {
      fileName = 'index.html';
    } else {
      fileName = `${url.slice(1)}/index.html`;
    }

    const filePath = toAbsolute(`./dist/client/${fileName}`);
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, renderedHtml);
    console.log(`  - Prerendered ${url} -> ${filePath}`);
  }

  // Generate sitemap.xml dynamically (excluding non-searchable pages like forgot/reset password and 404)
  console.log('Generating sitemap.xml dynamically...');
  const siteUrl = process.env.VITE_SITE_URL || 'https://secure-vault.com';
  const indexableRoutes = ['/', '/login', '/register'];
  const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${indexableRoutes.map(route => {
    const loc = `${siteUrl}${route === '/' ? '' : route}`;
    const priority = route === '/' ? '1.0' : '0.8';
    return `  <url>
    <loc>${loc}</loc>
    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${priority}</priority>
  </url>`;
}).join('\n')}
</urlset>
`;
  fs.writeFileSync(toAbsolute('./dist/client/sitemap.xml'), sitemapXml);
  console.log('  - Generated sitemap.xml successfully.');

  // Clean up server build directory (no longer needed)
  console.log('Cleaning up server bundle...');
  fs.rmSync(toAbsolute('./dist/server'), { recursive: true, force: true });
  console.log('Prerendering completed successfully.');
}

run().catch((err) => {
  console.error('Prerendering failed:', err);
  process.exit(1);
});
